import Provider from '@/components/Provider'
import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Navbar from '@/components/navbar/Navbar'

const montse = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Natural Cosmética 🌿',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${montse.className}
          bg-neutral-200
          dark:bg-neutral-900
          text-neutral-700
          dark:text-neutral-200
          cursor-default
          select-none
          overflow-x-hidden
          transition-all
        `}
      >
        <Provider>
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  )
}
