import Provider from '@/components/Provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '🌿 Natural Cosmética 🌿',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-neutral-200 dark:bg-neutral-900 text-neutral-900 dark:text-neutral-200 transition-all`}
      >
        <Provider>
          <main className="w-full min-h-screen grid grid-cols-1 grid-rows-[min-content_1fr]">
            <Navbar />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  )
}
